template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 4
template_sha = "1478be9fec4c72c68d0d1420c0f1ca9efbab27a4"

[replacements]
__UND2C__ = "sma"
__UNDEFINED__ = "Southern Sami"
__UND__ = "sma"
