template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 6
template_sha = "ebfffb4d3630c8dae1c5b61dc92850d1513a17ed"

[replacements]
__UND2C__ = "sma"
__UNDEFINED__ = "Southern Sami"
__UND__ = "sma"
